config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: :about
  resources :books, only:[:index,:show,:create,:edit,:update,:destroy] do
  resources :book_comments, only:[:create,:destroy]
    resource :favorites,only:[:create, :destroy]
  end
  resources :users, only:[:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :body, presence: true, length: { maximum: 200 }
  validates :title, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
belongs_to :user
belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction,  length: { maximum: 50 }

    # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:[:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @book_comment = BookComment.new
    # comment = BookComment.new(book_comment_params)
    # comment.user_id = current_user.id
    @comment.book_id = @book.id
    @comment.save
    # redirect_to request.referer

  end

  def destroy
    @comment = BookComment.new
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    # redirect_to request.referer
  end



  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # before_action :correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @comment = BookComment.new
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
    @books = Book.all
    # @user = current_user
    # flash.now[:alert] = 'メッセージを入力してください。'
    render:index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
    redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
    render "edit"
    end

  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

   # strong parameter
  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  # def correct_user
    # @book = Book.find(params[:id])
    # @user = @book.user
    # unless @user == current_user
    # redirect_to (books_path)
  # end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

    # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id)
    flash[:notice] = "You have updated user successfully."
    else
    render "edit"
    end
  end


  # strong parameter
  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

   def correct_user
     @user = User.find(params[:id])
     redirect_to(user_path(current_user)) unless @user == current_user
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
     <table>
        <tbody>
            <% book.book_comments.each do |book_comment| %>
            <tr>

              <td>
                <%= link_to user_path(book_comment.user), remote: true do %>
                  <%= image_tag book_comment.user.get_profile_image(100,100) %><br>
                  <%= book_comment.user.name %>
                <% end %>
              </td>
              <td><%= book_comment.comment %></td>
              <td>
                <% if book_comment.user == current_user %>
                  <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
                <% end %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>

            <%= form_with(model:[book, book_comment], local: false) do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100" %>
            <%= f.submit "send", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
            <% end %>

app/views/book_comments/create.js.erb
$(".new-comment").html("<%= j(render 'book_comments/comment', book: @book, book_comment: @book_comment) %>");
$("textarea").val('');

app/views/book_comments/destroy.js.erb
$(".new-comment").html("<%= j(render 'book_comments/comment', book: @book, book_comment: @comment) %>");

app/views/books/edit.html.erb
 <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>

     <% if @book.errors.any? %>
     <%= @book.errors.count %>errors prohibited this book from being saved:
      <ul>
     <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
      </ul>
     <% end %>


     <%= form_with model: @book do |f| %>
      <div class="form_grop">

       <h4>Title</h4>
       <%= f.text_field :title , class: "form-control book_title" %>
      </div>
      <div>
       <h4>Opinion</h4>
       <%= f.text_area :body , class: "form-control book_body" %>
      </div>
      <div>
        <%= f.submit 'Update Book', class: "btn btn-success" %>
      </div>
     <% end %>


       <%= link_to "Show", book_path(@book.id) %>
       |
       <%= link_to "Back", books_path %>
    </div>
   </div>
 </div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this book from being saved:
        <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
        </ul>
  <% end %>

<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'users/userinfor', user: current_user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
          </td>

          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>

          <td class=<%= "favorite-btn-"+ book.id.to_s %>><%= render "favorites/btn", book: book %></td>

          <td>コメント数：<%= book.book_comments.count %></td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'users/userinfor', user: @user, book: @new_book %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
              <%=image_tag @user.get_profile_image(100,100) %>
              <div><%= @user.name %></div>
              <% end %>
            </td>

            <td><%= link_to @book.title , book_path(@book) %></td>

            <td><%= @book.body %></td>

            <td class=<%= "favorite-btn-" + @book.id.to_s %>><%= render "favorites/btn", book: @book %></td>

             <td>コメント数：<%= @book.book_comments.count %></td>

            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete, "data-comfirm" => "Are u sure" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class=<%= "new-comment" %>><%= render "book_comments/comment", book: @book, book_comment: @comment %></div>

    </div>
  </div>
</div>

app/views/favorites/_btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/btn', book: @book) %>");

app/views/homes/about.html.erb
<div class = "container">
  <div class = "row">
    <h1 class= "px-3 mx-auto">Welcome to
    <i class="fas fa-book"></i>
    <strong>Bookers</strong>
    !
    </h1>
    </div>
</div>

app/views/homes/top.html.erb
<div class = "container">
  <div class = "row">
    <div class = "mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to<i class="fas fa-book"></i> <strong>Bookers</strong>!!</h1>

      <p>In<i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <!--ここから-->
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>

        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrushApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <a class="navbar-brand" href="/">Bookers</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>
          <li>
            <%=link_to user_path(current_user), class: "nav-link text-light" do %>
            <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li>
            <%= link_to users_path, class: "nav-link text-light" do %>
            <i class="fas fa-users"></i>Users
            <% end %>
          </li>
          <li>
            <%= link_to books_path, class: "nav-link text-light" do %>
            <i class="fas fa-book-open"></i>Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
            <i class="fas fa-sign-out-alt"></i>Log out
            <% end %>
          </li>

        <% else %>

          <li>
            <%= link_to root_path, class: "nav-link text-light" do %>
            <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li>
            <%= link_to about_path, class: "nav-link text-light" do %>
            <i class="fas fa-link"></i>About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
            <i class="fas fa-user-plus"></i>Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: "nav-link text-light" do %>
            <i class="fas fa-sign-in-alt"></i>Log in
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
      </div>
    </nav>
  </header>
  <%= flash[:notice] %>
  <%= flash[:alert] %>
    <%= yield %>
  </body>
  <footer>
    <div class='container mt-5'>
  	 <div class='row'>
      <div class='mx-auto'>
       <p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
  </footer>
</html>

app/views/relationships/_follow_list.html.erb
<% if users.exists? %>
    <table class = "table">
      <thead>
        <tr>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "show", user_path(user.id) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followers.html.erb
<h1>followers</h1>
<%= render "relationships/follow_list", users: @users %>

app/views/relationships/followings.html.erb
<h1>followings</h1>
<%= render "relationships/follow_list", users: @users %>

app/views/users/_userinfor.html.erb
  <div class="col-md-3">
      <h2>User info</h2>
      <%=image_tag user.get_profile_image(100,100) %>
      <table class="table">
        <tr></tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
        </tr>
      </table>
      <div class="mb-2">
           <% if current_user.following?(@user) %>
            <%= link_to "フォローを外す", user_relationships_path(@user.id), class: "btn btn-info", method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), class: "btn btn-success", method: :post %>
          <% end %>
          </div>
      <div class="row">
        <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <h1>New book</h1>

      <%= form_with model: book do |f| %>

      <h4>title</h4>
      <%= f.text_field :title %>

      <h4>body</h4>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book' %>

      <% end %>
  </div>

app/views/users/edit.html.erb
 <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h1>Use info</h1>

      <% if @user.errors.any? %>
      <%= @user.errors.count %>errors prohibited this book from being saved:
        <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
        </ul>
      <% end %>

      <%= form_with model: @user do |f| %>
       <div class="form_grop">
         <h4>Name</h4>
         <%= f.text_field :name , class: "form-control user_name" %>
       </div>

        <div>
         <h4>Image</h4>
         <%= f.file_field :profile_image , accept: "image/*" , class: "from-control uesr_profile_image" %>
        </div>

        <div>
         <h4>Introduction</h4>
         <%= f.text_area :introduction , class: "form-control user_introduction" %>
        </div>

        <div>
         <%= f.submit 'Update User', class: "btn btn-secondary" %>
        </div>
       <% end %>

    </div>
   </div>
 </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'userinfor', user: current_user,book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tboay>
          <% @users.each do |user| %>
          <tr>
            <td><%=image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <td>フォロー数：<%= user.followings.count %></td>
            <td>フォロワー数：<%= user.followers.count %></td>
            <td>
              <% if current_user.following?(user) %>
              　<%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            　<% else %>
              　<%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            　<% end %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tboay>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- ユーザーの詳細 -->
<div class='container px-5 px-sm-0'>

  <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this book from being saved:
        <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
        </ul>
  <% end %>
  <div class='row'>

    <%= render 'userinfor' , user: @user , book: @book %>

    <!-- ユーザーの投稿一覧 -->
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                <%= image_tag @user.get_profile_image(100,100) %></td>
                <% end %>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>